### PR TITLE
add moneroTs default export

### LINKED ISSUE #146: Support import syntax: `import moneroTs from "monero-ts"`
Currently importing all types from monero-ts requires the syntax:

`import * as moneroTs from "monero-ts";`

This issue requests supporting the following syntax with equivalent functionality:

`import moneroTs from "monero-ts";`

### PR DESCRIPTION
**Pull request by dutu**
This PR adds moneroTs default export so that the module can be imported as:
```js
import moneroTs from "monero-ts";
```

Resolves #146

### CODE REVIEW

**Comment by woodser** [comment]
Thanks. I'm seeing an error when I apply this PR and use the `import moneroTs from "monero-ts";` syntax: "Cannot find namespace 'moneroTs'.ts(2503)".

For example, this error can be observed by editing TestSampleCode.ts to `import moneroTs from "../../index";` and it will cause a compile error on `moneroTs.MoneroWalletFull`. I see the same when importing monero-ts from an external project.

**Comment by dutu** [comment]
Sorry, I have been testing and using the change on JavaScript, which works both with named and default export/import. It looks that TypeScript handles is differently. 
Will check it out.

**Comment by dutu** [comment]
The usage of `moneroTs.MoneroWalletFull`, as seen in `TestSampleCode.ts`, is expected to function as both a value and a type. 

This presents a challenge with TypeScript's handling of default imports. In such cases, TypeScript does not inherently interpret the properties of an imported object as namespaces or types. It results in `moneroTs` being recognized as an object, not a namespace. Consequently, its properties are treated only as values, leading to `Cannot find namespace` error when using `moneroTs.MoneroWalletFull` as a type.

(When using named imports, TypeScript infers types directly from the module's export definitions, allowing for straightforward usage of these types as they are explicitly defined and exported).

One approach to address this issue is to exporting the types separately (e.g. `type MoneroWalletFullType = MoneroWalletFull`). However, this approach would necessitate extensive modifications across the codebase wherever `MoneroWalletFull` is used as a type, which could be impractical.

A more appropriate solution in this scenario would be to declare a global namespace `moneroTs`. This declaration augments the global scope with a namespace that matches the name of the default-exported object. Consequently, it establishes a correspondence between the structure of the default-exported object and a globally accessible namespace. This enables TypeScript to recognize and interpret the properties of the `moneroTs` object as types, resolving the `Cannot find namespace error` without necessitating widespread codebase modifications.

```ts
declare global {
    namespace moneroTs {
        type MoneroWalletFull = InstanceType<typeof import("./index").MoneroWalletFull>;
    }
}
```

**Comment by dutu** [comment]
I have updated the PR, would you be able to test it? I'm not able to fully test since I don't have the entire test environment set up.

**Comment by woodser** [comment]
Please rebase on the latest master.

**Comment by dutu** [comment]
Pls check

**Comment by woodser** [comment]
Thanks, it's working. :)

I've created a PR to your branch for minor cleanup: https://github.com/dutu/monero-ts/pull/1

Please merge, squash, and rebase on the latest master so it can be merged.

Let's only change index.ts and none of the ./dist files, since ./dist will be updated in a single commit before release.

**Comment by dutu** [comment]
Should be ok now

**Comment by woodser** [comment]
Looks like it needs squashed to resolve the merge conflicts.

**Comment by dutu** [comment]
It doesn't show any conflict but I'll do it
image

**Comment by woodser** [comment]
Strange, it shows conflicts for me:

image

**Comment by dutu** [comment]
I'm getting strange git behaviorus and won't take more time to troubleshoot. I've created a new PR and will be closing this one. Please merge the new PR, or feel free make own version with suggested changes.

**Pull request closed without merging**
